import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';
type PrivacyMode = 'active' | 'approximate';

interface SettingsContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  notificationsEnabled: boolean;
  setNotificationsEnabled: (enabled: boolean) => void;
  privacyMode: PrivacyMode;
  setPrivacyMode: (mode: PrivacyMode) => void;
  darkMode: boolean;
  setDarkMode: (enabled: boolean) => void;
  t: (key: string) => string;
  showAlert: (title: string, message: string) => void;
  showConfirm: (title: string, message: string, onConfirm: () => void) => void;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    'common.by': 'Por',
    'common.ecowarrior': 'EcoWarrior',
    'common.admin': 'Administrador',
    'community.squad_status_upcoming': 'Próxima',
    'community.squad_status_finished': 'Finalizada',
    'community.squad_status_cancelled': 'Cancelada',
    'community.squad_time_label': 'Hora',
    'community.squad_desc_placeholder': '¿Qué se va a hacer? ¿Qué herramientas traer?',
    'community.squad_location_placeholder': 'Ej: Plaza Central, Av. Rivadavia 100',
    'community.squad_max_participants_label': 'Máx. Participantes (0 para ilimitado)',
    'community.squad_save_button': 'GUARDAR CUADRILLA',
    'community.squad_creating_button': 'CREANDO...',
    'community.squad_save_changes': 'GUARDAR CAMBIOS',
    'community.squad_create_btn': 'CREAR CUADRILLA',
    'community.squad_edit_title': 'Editar Cuadrilla',
    'community.squad_create_title': 'Crear Nueva Cuadrilla',
    'community.squad_title_label': 'Título de la Acción',
    'community.squad_title_placeholder': 'Ej: Limpieza de Desagües Norte',
    'community.squad_attendees_title': 'Inscriptos en la Cuadrilla',
    'community.people_joined': 'personas se han sumado',
    'community.squad_attendees': 'Asistentes',
    'community.squad_leave': 'Abandonar Cuadrilla',
    'community.squad_join': 'Unirme a la Cuadrilla',
    'community.cancel_squad_title': 'Cancelar Cuadrilla',
    'community.cancel_squad_confirm': '¿Estás seguro de que quieres cancelar esta cuadrilla? Se notificará a los asistentes.',
    'nav.dashboard': 'Dashboard',
    'nav.reports': 'Reportes',
    'nav.community': 'Comunidad',
    'nav.map': 'Mapa',
    'nav.chatbot': 'Rocco AI',
    'nav.profile': 'Perfil',
    'nav.logout': 'Cerrar Sesión',
    'nav.crisis_mode': 'Modo Crisis',
    'feedback.button': 'Feedback',
    'feedback.title': 'Queremos saber tu opinión',
    'feedback.description': 'Tu feedback nos ayuda a mejorar EcoWarriors y generar un mayor impacto en la comunidad.',
    'feedback.respond_form': 'Responder formulario',
    'feedback.respond_form_new_tab': 'Responder formulario (se abre en una nueva pestaña)',
    'nav.resilience': 'Resiliencia Ciudadana',
    'landing.login': 'Iniciar sesión',
    'landing.signup': 'Crear cuenta',
    'landing.hero_badge': 'Red de Resiliencia Urbana',
    'landing.hero_title_1': 'La basura no solo',
    'landing.hero_title_2': 'ensucia',
    'landing.hero_title_3': 'inunda',
    'landing.hero_subtitle': 'Convertite en sensor activo de tu barrio y ayudanos a prevenir desastres hídricos.',
    'landing.about_title': 'Quiénes Somos',
    'landing.about_subtitle': 'Un equipo comprometido con la transformación de nuestras ciudades a través de la tecnología y la acción comunitaria.',
    'landing.impact_title': 'Tu Impacto',
    'landing.impact_subtitle': 'Cada reporte y cada acción contribuye directamente a los Objetivos de Desarrollo Sostenible de la ONU.',
    'landing.edu_title': '¿Sabías que un desagüe obstruido multiplica el riesgo de inundación?',
    'landing.edu_desc': 'Los residuos arrojados en la vía pública terminan en los sumideros, reduciendo su capacidad de drenaje en un 70%. Tu reporte temprano permite una limpieza preventiva antes de la tormenta.',
    'landing.stat_obstruction': 'Obstrucción',
    'landing.stat_obstruction_desc': 'de capacidad perdida',
    'landing.stat_prevention': 'Prevención',
    'landing.stat_prevention_desc': 'antes de la lluvia',
    'landing.stat_impact': 'Impacto',
    'landing.stat_impact_desc': 'menos daños materiales',
    'landing.support_thanks_title': 'Gracias a quienes nos dieron espacio para compartir nuestra idea y hacerla crecer',
    'landing.support_thanks_subtitle': 'Estos espacios, instituciones y empresas impulsaron nuestro camino para transformar la conciencia ambiental en acción comunitaria.',
    'landing.support_gallery_title': 'Galería del proyecto',
    'landing.support_gallery_subtitle': 'Momentos reales de nuestro equipo presentando EcoWarriors y construyendo redes para generar impacto.',
    'landing.security_title': 'Compromiso de Seguridad',
    'landing.security_subtitle': 'Tu seguridad es nuestra prioridad número uno.',
    'landing.security_rule_1': 'Nunca te acerques a zonas de peligro inminente o cables caídos.',
    'landing.security_rule_2': 'Usa la aplicación solo desde lugares seguros y estables.',
    'landing.security_rule_3': 'En caso de emergencia real, llamá siempre al 911 primero.',
    'landing.security_accept': 'Entiendo y acepto las normas de seguridad',
    'landing.directory_title': 'Directorio Útil',
    'landing.directory_subtitle': 'Acceso rápido a los números de emergencia y servicios públicos esenciales de tu zona.',
    'landing.directory_emergencies': 'Emergencias',
    'landing.directory_civil_defense': 'Defensa Civil',
    'landing.directory_firefighters': 'Bomberos',
    'landing.ready_title': '¿Listo para empezar?',
    'landing.ready_desc': 'Unite a Sarah, Brune, Agus, Delfi, Martu y cientos de vecinos que ya están cuidando su barrio.',
    'landing.start_now': 'EMPEZAR AHORA',
    'landing.security_warning': 'Debes aceptar las normas de seguridad para continuar',
    'landing.footer_copy': '© 2026 EcoWarriors. Hecho con amor por el planeta.',
    'reports.filter_open': 'Abiertos',
    'reports.filter_resolved': 'Resueltos',
    'reports.filter_mine': 'Míos',
    'reports.title_all': 'Todos los Reportes',
    'reports.title_mine': 'Mis Reportes',
    'reports.desc_all': 'Explora la situación ambiental de la comunidad',
    'reports.desc_mine': 'Gestiona tus contribuciones ambientales',
    'reports.new_report': 'Nuevo Reporte',
    'reports.search_placeholder': 'Buscar reportes...',
    'reports.cancelled': '(Cancelado)',
    'marketplace.title': 'Mercado Solidario',
    'marketplace.desc': 'Intercambio de recursos y herramientas entre vecinos',
    'marketplace.banner_title': '¿Cómo funciona el Mercado?',
    'marketplace.banner_desc': 'Publicá herramientas que ya no uses o pedí lo que necesites para mejorar tu zona. Fomentamos la economía circular y la ayuda mutua.',
    'marketplace.filter_all': 'Todos',
    'marketplace.filter_available': 'Disponible',
    'marketplace.filter_reserved': 'Reservado',
    'marketplace.filter_expired': 'Vencido',
    'marketplace.search_placeholder': 'Buscar en el mercado...',
    'marketplace.no_posts': 'No se encontraron publicaciones',
    'marketplace.no_posts_desc': 'Probá con otros filtros o términos de búsqueda',
    'marketplace.offer': 'OFREZCO',
    'marketplace.banner_button': 'Entendido',
    'marketplace.need': 'NECESITO',
    'marketplace.active_neighbor': 'Vecino Activo',
    'marketplace.details': 'Detalles',
    'community.title': 'COMUNIDAD',
    'community.squads': 'Cuadrillas',
    'community.no_events': 'No hay eventos próximos',
    'community.enrolled': 'Inscrito',
    'community.join_squad': 'Unirme a la Cuadrilla',
    'community.what_is_squad': '¿Qué es una cuadrilla?',
    'community.squad_desc': 'Son grupos de vecinos organizados para acciones rápidas: limpieza de desagües, remoción de escombros o ayuda logística post-tormenta.',
    'community.no_squads': 'No hay cuadrillas programadas aún.',
    'community.active_warriors': 'EcoWarriors activos en tu zona.',
    'community.be_first': 'Sé el primero en tu zona en reportar.',
    'community.scheduled_crews': 'cuadrilla programada próximamente.',
    'community.scheduled_crews_plural': 'cuadrillas programadas próximamente.',
    'mission.reward_label': 'XP',
    'mission.status_in_progress': 'En progreso',
    'mission.status_available': 'Disponible',
    'mission.description': 'Descripción',
    'mission.objective': 'Objetivo',
    'mission.suggested_action': 'Acción sugerida',
    'mission.close': 'Cerrar',
    'mission.title_primer-reporte': 'Primer Reporte',
    'mission.desc_primer-reporte': 'Crear un reporte con imagen',
    'mission.obj_primer-reporte': 'Documentar visualmente un problema ambiental para facilitar su identificación.',
    'mission.action_primer-reporte': 'Buscá un problema en tu zona, tomá una foto y reportalo.',
    'mission.title_ojo-aguila': 'Ojo de Águila',
    'mission.desc_ojo-aguila': 'Reportar una zona no previamente reportada',
    'mission.obj_ojo-aguila': 'Expandir la cobertura del mapa de EcoWarriors a nuevas áreas.',
    'mission.action_ojo-aguila': 'Explorá una zona del mapa que no tenga reportes activos y creá uno.',
    'mission.title_ojo-critico': 'Ojo Crítico',
    'mission.desc_ojo-critico': 'Agregar una actualización a un reporte existente',
    'mission.obj_ojo-critico': 'Mantener la información actualizada para un mejor seguimiento.',
    'mission.action_ojo-critico': 'Buscá un reporte cercano y agregá un comentario o foto sobre su estado actual.',
    'mission.title_cierre-responsable': 'Cierre Responsable',
    'mission.desc_cierre-responsable': 'Marcar un reporte como resuelto con evidencia',
    'mission.obj_cierre-responsable': 'Confirmar la resolución de problemas con pruebas visuales.',
    'mission.action_cierre-responsable': 'Cuando veas que un problema se solucionó, actualizalo a "Resuelto" subiendo una foto.',
    'mission.title_accion-comunitaria': 'Acción Comunitaria',
    'mission.desc_accion-comunitaria': 'Inscribirse a una cuadrilla',
    'mission.obj_accion-comunitaria': 'Fomentar la participación en actividades grupales de impacto.',
    'mission.action_accion-comunitaria': 'Unite a una de las cuadrillas activas en la pestaña de Comunidad.',
    'mission.title_prevencion-activa': 'Prevención Activa',
    'mission.desc_prevencion-activa': 'Configurar un contacto y usar Modo Crisis',
    'mission.obj_prevencion-activa': 'Estar preparado para situaciones de emergencia.',
    'mission.action_prevencion-activa': 'Completá el onboarding del Modo Crisis y configurá tus contactos de confianza.',
    'achievement.title_first-report': 'Primer Reporte',
    'achievement.desc_first-report': 'Documentaste tu primer problema ambiental.',
    'achievement.title_problem-solver': 'Solucionador',
    'achievement.desc_problem-solver': 'Ayudaste a resolver al menos un reporte.',
    'achievement.title_community-hero': 'Héroe Comunitario',
    'achievement.desc_community-hero': 'Participaste en tu primera cuadrilla.',
    'achievement.title_active-guardian': 'Guardián Activo',
    'achievement.title_crisis-responder': 'Rescatista',
    'achievement.title_squad-leader': 'Líder de Cuadrilla',
    'achievement.title_environmental-expert': 'Experto Ambiental',
    'achievement.desc_active-guardian': 'Realizaste más de 5 reportes.',
    'community.weather_current': 'Clima actual',
    'community.weather_loading': 'Cargando datos del clima...',
    'profile.title': 'Perfil de EcoWarrior',
    'profile.reports': 'Reportes',
    'profile.resolved': 'Resueltos',
    'profile.xp': 'Puntos XP',
    'profile.level': 'Nivel',
    'profile.zone': 'Zona',
    'profile.commitment': 'Compromiso',
    'profile.missions': 'Misiones de Rocco',
    'profile.ranking': 'Ranking',
    'profile.my_reports': 'Mis Reportes',
    'profile.settings': 'Configuración',
    'profile.notifications': 'Notificaciones',
    'profile.language': 'Idioma',
    'profile.privacy': 'Privacidad',
    'profile.privacy_exact': 'Ubicación exacta',
    'profile.privacy_exact_desc': 'Otros usuarios verán tu ubicación exacta para una respuesta más rápida.',
    'profile.privacy_approximate': 'Zona aproximada',
    'profile.privacy_approximate_desc': 'Solo se mostrará una zona general para proteger tu privacidad.',
    'profile.privacy_modal_title': 'Privacidad de ubicación',
    'profile.privacy_modal_desc': 'Elegí cómo querés que se muestre tu ubicación en los reportes.',
    'profile.logout': 'Cerrar Sesión',
    'profile.active': 'Activo',
    'profile.inactive': 'Inactivo',
    'reports.mine': 'Mis Reportes',
    'reports.all': 'Reportes Activos',
    'reports.mine_desc': 'Tus contribuciones a la red de resiliencia',
    'reports.all_desc': 'Monitoreo de incidentes ambientales y crisis',
    'reports.filter_all': 'Todos',
    'reports.search': 'Buscar reportes...',
    'reports.empty_mine': 'No tenés reportes aún',
    'reports.empty_all': 'No hay reportes activos',
    'reports.empty_mine_desc': 'Tus reportes aparecerán aquí una vez que los crees.',
    'reports.empty_all_desc': 'Sé el primero en reportar un incidente en tu zona para ayudar a la comunidad.',
    'reports.status_all': 'Todos los estados',
    'reports.status_pending': 'Pendientes',
    'reports.status_verified': 'Verificados',
    'reports.status_resolved': 'Resueltos',
    'profile.recent_reports': 'Mis Reportes Recientes',
    'profile.view_all': 'Ver todos',
    'profile.view_less': 'Ver menos',
    'profile.view.less': 'Ver menos',
    'profile.manage_reports': 'Gestionar Reportes',
    'profile.manage_reports_desc': 'Seguimiento detallado de tus alertas',
    'profile.ranking_title': 'Ranking',
    'profile.top_agents': 'Top 5 Agentes',
    'profile.xp_accumulated': 'XP acumulados',
    'profile.dark_mode': 'Modo Oscuro',
    'error.profile_not_found': 'No se pudo encontrar el perfil de usuario.',
    'error.server_connection': 'Error al conectar con el servidor.',
    'common.close': 'Cerrar',
    'common.description': 'Descripción',
    'common.objective': 'Objetivo',
    'common.completed': 'Completada',
    'common.in_progress': 'En curso',
    'common.rocco_suggestion': 'Sugerencia de Rocco',
    'common.active_sensor': 'Sensor Activo',
    'common.report': 'Reportar',
    'common.volunteer_signup': 'Inscripción de Voluntario',
    'crisis.title': 'Modo Crisis',
    'crisis.im_ok': 'Estoy Bien',
    'crisis.im_safe_title': '¿ESTÁS A SALVO?',
    'crisis.im_safe_desc': 'Envía tu ubicación y estado a tus contactos',
    'crisis.sent': 'ENVIADA',
    'crisis.report_damage': 'Reportar Daño',
    'crisis.meeting_point': 'Punto de Encuentro',
    'crisis.guide': 'Guía de Servicios',
    'crisis.backpack': 'Mochila',
    'crisis.exit': 'Salir del Modo Crisis',
    'crisis.finish': 'Finalizar Crisis',
    'crisis.add_contact': 'Agregar Contacto de Confianza',
    'crisis.activate': 'Activar Alerta',
    'crisis.preventive_reminders': 'Recordatorios Preventivos',
    'crisis.reminders_desc': 'Revisión de agua y pilas cada 4hs',
    'crisis.emergency_call': 'LLAMAR',
    'crisis.back': 'VOLVER',
    'crisis.edit_contact': 'Editar Contacto',
    'crisis.safe_message': 'ESTOY BIEN. Mi ubicación actual:',
    'crisis.safe_message_no_gps': 'ESTOY BIEN. (No se pudo obtener ubicación exacta)',
    'crisis.onboarding_title': 'BIENVENIDO AL MODO CRISIS',
    'crisis.onboarding_desc': 'Una herramienta diseñada para mantenerte a salvo durante eventos climáticos extremos.',
    'crisis.onboarding_contacts_title': 'CONTACTOS DE CONFIANZA',
    'crisis.onboarding_contacts_desc': 'Configura quién recibirá tu señal de "Estoy a salvo" con tu ubicación exacta.',
    'crisis.contact_name_label': 'Nombre del Contacto',
    'crisis.contact_phone_label': 'WhatsApp (con código de país)',
    'crisis.save_continue': 'GUARDAR Y CONTINUAR',
    'crisis.ready_title': '¡TODO LISTO!',
    'crisis.ready_desc': 'Ya puedes usar el Modo Crisis. Recuerda que esta herramienta es para emergencias.',
    'crisis.start': 'COMENZAR',
    'crisis.signal_active': 'Señal: Activa',
    'crisis.version': 'EcoWarriors Crisis v1.0',
    'crisis.no_contact_warning': 'Configurá un contacto de confianza para usar esta función.',
    'crisis.location_error': 'Error obteniendo ubicación',
    'crisis.signal_sent_success': 'Señal enviada con éxito.',
    'crisis.offline_warning': 'Sin conexión. La señal se enviará cuando recuperes internet.',
    'dashboard.crisis_mode': 'Modo Crisis',
    'dashboard.activate_now': 'Activar ahora',
    'dashboard.activate_crisis': 'Activar Modo Crisis',
    'dashboard.no_squads': 'No hay cuadrillas programadas por el momento. ¡Creá una desde la sección Comunidad!',
    'dashboard.view_profile': 'Ver en mi Perfil',
    'dashboard.level_progress': 'Nivel {level} • Progreso de Rango',
    'dashboard.squad_event': 'Evento de Cuadrilla',
    'community.search_board': 'Buscar en el tablón...',
    'community.volunteer_zone': 'Barrio o Localidad',
    'reports.urgency_1': 'Nivel 1: Bajo',
    'reports.urgency_2': 'Nivel 2: Informativo',
    'reports.urgency_3': 'Nivel 3: Atención',
    'reports.urgency_4': 'Nivel 4: Seguimiento',
    'reports.urgency_5': 'Nivel 5: Crítico',
    'map.flood_risk': 'Zona de riesgo de anegamiento moderado',
    'map.road_risk': 'Zona de alto tráfico y riesgo de accidentes',
    'map.energy_point': 'Subestación Eléctrica - Operativa',
    'map.loading': 'Cargando mapa colaborativo...',
    'dashboard.weather_in': 'Clima en',
    'dashboard.rocco_tip_title': 'Tip de Rocco',
    'weather.partly_cloudy': 'Parcialmente nublado',
    'onboarding.zone_placeholder': 'Tu zona o barrio',
    'reports.environmental': 'Ambiental',
    'reports.crisis': 'Crisis',
    'reports.title_label': 'Título del Reporte',
    'reports.title_placeholder': 'Ej: Basural en la esquina',
    'reports.description_label': 'Descripción',
    'reports.description_placeholder': 'Describe el problema detalladamente...',
    'reports.visual_evidence': 'Evidencia Visual',
    'reports.location_label': 'Ubicación',
    'reports.location_not_detected': 'Ubicación no detectada',
    'reports.analyze_button': 'Enviar reporte',
    'reports.upload_photo': 'Subir Foto',
    'reports.getting_gps': 'Obteniendo GPS...',
    'reports.geolocation_not_supported': 'Geolocalización no compatible.',
    'reports.coords_label': 'Coordenadas',
    'reports.location_error': 'Error de ubicación',
    'reports.wait_location': 'Esperando ubicación...',
    'reports.fill_all_fields': 'Por favor, completa todos los campos.',
    'reports.analyzing': 'Analizando...',
    'reports.ai_analysis': 'Análisis de IA',
    'reports.suggested_category': 'Categoría sugerida',
    'reports.urgency_level': 'Nivel de urgencia',
    'reports.urgency_value': 'Nivel {level}',
    'reports.correct_data': '¿Los datos son correctos?',
    'reports.confirm_publish': 'Confirmar y Publicar',
    'map.search_placeholder': 'Buscar ubicación o lugar...',
    'map.early_warning': 'Sistema de Alerta Temprana',
    'map.real_time_monitoring': 'Monitoreo en tiempo real',
    'map.update_report': 'Actualizar Reporte',
    'common.save_changes': 'Guardar Cambios',
    'common.retry': 'Reintentar',
    'common.loading': 'Cargando...',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.success': 'Éxito',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.edit_profile': 'Editar Perfil',
    'common.username_alias': 'Nombre de Usuario / Alias',
    'common.new_alias_placeholder': 'Tu nuevo alias...',
    'common.photo_updated': 'Foto actualizada',
    'common.invalid_image': 'Por favor, selecciona una imagen válida.',
    'common.upload_error': 'Error al subir la foto.',
    'common.profile_not_found': 'Perfil no encontrado',
    'common.server_connection_error': 'Error de conexión con el servidor',
    'reports.confirm_report': 'Confirmar Reporte',
    'reports.create_error': 'Error al crear el reporte. Inténtalo de nuevo.',
    'reports.create_success': 'Reporte creado con éxito. ¡Gracias por tu compromiso!',
    'reports.invalid_coords': 'La ubicación debe contener coordenadas válidas (latitud y longitud).',
    'reports.zone': 'Zona',
    'reports.commitment': 'Compromiso',
    'reports.undefined': 'Sin definir',
    'reports.optional': 'Opcional',
    'reports.resolved': 'Resuelto',
    'reports.crisis_alert': 'ALERTA DE CRISIS: Sin imagen de evidencia',
    'reports.manual_coords': 'Coordenadas Manuales',
    'reports.traceability_system': 'Sistema de Trazabilidad EcoWarriors',
    'common.ecowarriors': 'EcoWarriors',
    'common.ai_verified': 'Verificado por IA',
    'common.xp_points': 'Puntos XP',
    'common.info': 'Información',
    'common.voice_input': 'Entrada de voz',
    'weather.clear': 'Despejado',
    'reports.no_coords': 'Sin coordenadas',
    'landing.light_mode': 'Modo Claro',
    'landing.dark_mode': 'Modo Oscuro',
    'dashboard.default_zone': 'Zona predeterminada',
    'rocco.welcome': '¡Hola! Soy Rocco, tu mentor ambiental. ¿En qué puedo ayudarte hoy?',
    'rocco.suggested_1': '¿Cómo puedo prevenir inundaciones?',
    'rocco.suggested_2': '¿Qué hacer con los residuos electrónicos?',
    'rocco.suggested_3': '¿Cómo armar una mochila de emergencia?',
    'rocco.suggested_4': 'Contame sobre la economía circular',
    'rocco.mentor_online': 'Mentor Online',
    'rocco.reset_chat': 'Reiniciar chat',
    'rocco.placeholder': 'Pregúntale a Rocco...',
    'rocco.error_connection': '¡Ups! Parece que mi conexión con la red ambiental falló. Por favor, intenta de nuevo en un momento.',
    'rocco.error_processing': '¡Ups! Parece que mi conexión con la red ambiental falló. Por favor, intenta de nuevo en un momento.',
    'rocco.rate_limit_message': 'Estás enviando mensajes demasiado rápido. Esperá {seconds}s para volver a escribir.',
    'rocco.system_instruction': 'Sos Rocco, el asistente de inteligencia artificial de EcoWarriors: Resiliencia Urbana. Tu único rol es ayudar a los usuarios con temas directamente relacionados a esta aplicación y su contexto. Podés responder sobre: cómo usar la app (reportes, cuadrillas, misiones, mapa, marketplace, modo crisis), ecología urbana, contaminación ambiental, gestión de residuos, prevención de inundaciones, emergencias climáticas, economía circular y sustentabilidad urbana. Si el usuario pregunta algo que NO esté relacionado con estos temas (por ejemplo, recetas de cocina, deportes, política, entretenimiento, matemáticas, código, etc.), respondé exactamente esto: "Solo puedo ayudarte con temas relacionados a EcoWarriors y el medio ambiente urbano. ¿Tenés alguna consulta sobre la app o el cuidado del barrio?" No respondas preguntas fuera de tema bajo ninguna circunstancia, aunque el usuario insista. Respondé siempre en {lang}.',
    'rocco.missions_title': 'Misiones de Rocco',
    'rocco.view_progress': 'Ver detalles',
    'rocco.all_completed': '¡Completaste todas tus misiones! 🎉',
    'rocco.no_missions': 'Completa acciones para desbloquear misiones',
    'rocco.tip_title': 'Tip del Día',
    'rocco.tip_desc': 'El mejor residuo es el que no se genera. Antes de comprar, piensa si realmente lo necesitas.',
    'rocco.tip_help': '¿Puedes contarme más sobre este concepto? "{tip}"',
    'rocco.learn_more': 'Saber más',
    'rocco.mission_help': 'Necesito ayuda con esta misión: "{title}". {description}. ¿Qué me recomiendas para completarla?',
    'rocco.voice_soon': 'La entrada de voz estará disponible próximamente.',
    'common.view_in_profile': 'Ver en mi Perfil',
    'community.volunteer_signup': 'Registro de Voluntarios',
    'community.volunteer_signup_desc': 'Al registrarte, te sumas a nuestra red de contacto para acciones de emergencia o limpiezas programadas. Tus datos son privados y solo serán usados para coordinar ayuda.',
    'community.volunteer_name_label': 'Nombre o Alias',
    'community.volunteer_name_placeholder': '¿Cómo te llamamos?',
    'community.volunteer_contact_label': 'Contacto Directo',
    'community.volunteer_contact_placeholder': 'WhatsApp o Email',
    'community.volunteer_help_label': '¿En qué puedes ayudar? (Opcional)',
    'community.volunteer_help_placeholder': 'Ej: Tengo camioneta, sé de logística, limpieza pesada...',
    'community.volunteer_confirm': 'CONFIRMAR REGISTRO',
    'community.post_type_offer': 'Nueva Donación (Doy)',
    'community.post_type_need': 'Pedir Ayuda (Necesito)',
    'community.post_photos_label': 'Fotos (1-5)',
    'community.post_title_label': 'Título',
    'community.post_title_placeholder': 'Ej: Ropa de abrigo, Alimentos...',
    'community.post_tag_label': 'Etiqueta',
    'community.post_details_label': 'Detalles',
    'community.post_details_placeholder': 'Añade información relevante...',
    'community.post_contact_label': 'Contacto',
    'community.post_contact_placeholder': 'WhatsApp o Redes...',
    'community.post_publish': 'PUBLICAR',
    'community.squad_event': 'Evento de Cuadrilla',
    'community.tag_ropa': 'Ropa',
    'community.tag_comida': 'Comida',
    'community.tag_otros': 'Otros',
    'community.date_label': 'Fecha',
    'community.location_label': 'Lugar',
    'community.description_label': 'Descripción',
    'community.participants_label': 'Participantes',
    'community.neighbors_label': 'Vecinos',
    'community.im_attending': '¡Asistiré!',
    'community.join_button': 'Sumarme',
    'community.manage_status': 'Gestionar Estado',
    'crisis.manual_coords': 'Coordenadas Manuales',
    'crisis.gps_location': 'Ubicación GPS',
    'crisis.use_gps': 'Usar GPS',
    'crisis.enter_manually': 'Ingresar manualmente',
    'crisis.coords_required': 'Las coordenadas son obligatorias',
    'crisis.urgency_high': 'Alta',
    'crisis.urgency_critical': 'Crítica',
    'crisis.sending': 'Enviando...',
    'crisis.send_report': 'Enviar Reporte',
    'crisis.upload_damage_photo': 'Subir foto del daño',
    'crisis.damage_type': 'Tipo de Daño',
    'crisis.select_damage': 'Selecciona tipo de daño',
    'crisis.roof_damage': 'Voladura de techo',
    'crisis.house_collapse': 'Colapso de vivienda',
    'crisis.severe_flood': 'Inundación grave',
    'crisis.other_damage': 'Otro daño',
    'crisis.report_help_text': 'Este reporte ayuda a priorizar asistencia comunitaria. Si hay riesgo de vida inminente, llama al 911.',
    'crisis.visual_evidence': 'Evidencia Visual (Opcional)',
    'crisis.report_success': 'Reporte de crisis enviado y reflejado en el mapa colaborativo.',
    'crisis.offline_report_success': 'Sin conexión o sesión. Tu reporte de crisis ha sido guardado localmente y se enviará al recuperar la señal.',
    'crisis.electricity_guide': 'Electricidad (Luz)',
    'crisis.gas_guide': 'Gas',
    'crisis.water_guide': 'Agua',
    'crisis.guide_warning': 'Advertencia',
    'crisis.backpack_cat_food': 'Agua y Alimentos',
    'crisis.backpack_item_water': 'Agua (2L por persona/día)',
    'crisis.backpack_item_food': 'Alimentos no perecederos',
    'crisis.backpack_item_opener': 'Abridor de latas manual',
    'crisis.backpack_item_utensils': 'Utensilios básicos',
    'crisis.backpack_cat_docs': 'Documentación',
    'crisis.backpack_item_id': 'DNI/Pasaporte (físico o copia)',
    'crisis.backpack_item_titles': 'Títulos de propiedad/Alquiler',
    'crisis.backpack_item_insurance': 'Seguros médicos',
    'crisis.backpack_item_cash': 'Dinero en efectivo',
    'crisis.backpack_cat_health': 'Salud e Higiene',
    'crisis.backpack_item_firstaid': 'Botiquín de primeros auxilios',
    'crisis.backpack_item_meds': 'Medicamentos recetados',
    'crisis.backpack_item_alcohol': 'Alcohol en gel',
    'crisis.backpack_item_soap': 'Jabón y toallas',
    'crisis.backpack_cat_tools': 'Abrigo y Herramientas',
    'crisis.backpack_item_blanket': 'Manta térmica o bolsa de dormir',
    'crisis.backpack_item_clothes': 'Ropa de cambio',
    'crisis.backpack_item_flashlight': 'Linterna y pilas de repuesto',
    'crisis.backpack_item_radio': 'Radio AM/FM a pilas',
    'crisis.backpack_item_whistle': 'Silbato',
    'crisis.elec_step1': 'Ubique el tablero principal.',
    'crisis.elec_step2': 'Baje la llave térmica general.',
    'crisis.elec_step3': 'No toque el tablero si está mojado o hay agua alrededor.',
    'crisis.elec_warning': 'Peligro de electrocución si hay inundación.',
    'crisis.gas_step1': 'Ubique la llave de paso (cerca del medidor).',
    'crisis.gas_step2': 'Gire la manija 90 grados (posición perpendicular al caño).',
    'crisis.gas_step3': 'Si huele a gas, no encienda luces ni fósforos.',
    'crisis.gas_warning': 'Cierre el gas ante sospecha de fugas o daños estructurales.',
    'crisis.water_step1': 'Ubique la llave de paso general.',
    'crisis.water_step2': 'Gire en sentido de las agujas del reloj hasta que tope.',
    'crisis.water_step3': 'Llene recipientes limpios antes de cortar si es posible.',
    'crisis.water_warning': 'Evite consumir agua de red si hay sospecha de contaminación.',
    'reports.status_new': 'Abierto (nuevo)',
    'reports.status_followup': 'Abierto (en seguimiento)',
    'reports.status_aggravated': 'Abierto (agravado)',
    'reports.status_cancelled': 'Cancelado',
    'reports.no_image': 'Sin Imagen',
    'reports.delete_confirm': '¿Eliminar este reporte permanentemente?',
    'reports.cancel_confirm': '¿Cancelar este reporte? Se marcará como cargado por error.',
    'reports.delete_admin': 'Eliminar reporte (admin)',
    'reports.cancel_mine': 'Cancelar mi reporte',
    'reports.details': 'Detalles',
    'reports.recent': 'Reciente',
    'reports.location_unavailable': 'Ubicación no disponible',
    'reports.mode_crisis': 'MODO CRISIS',
    'reports.mode_environmental': 'AMBIENTAL',
    'reports.priority_label': 'Prioridad',
    'reports.priority_high': 'Alta',
    'reports.priority_medium': 'Media',
    'reports.priority_low': 'Baja',
    'reports.verifications_label': 'Verificaciones',
    'reports.verifications_count': '{count} {unit}',
    'reports.neighbor': 'Vecino',
    'reports.neighbors': 'Vecinos',
    'reports.view_history': 'Ver Historial Completo',
    'reports.system_status': 'Estado del Sistema',
    'reports.reported_on': 'Reportado el',
    'reports.by': 'Por',
    'reports.no_evidence_image': 'Sin Imagen de Evidencia',
    'map.base_layer': 'Mapa Base',
    'map.citizen_reports': 'Reportes Ciudadanos',
    'map.flood_layer': 'Inundaciones / Anegamientos',
    'map.energy_layer': 'Puntos de Energía',
    'map.road_layer': 'Riesgo Vial',
    'map.emergency': 'Emergencia',
    'map.alert_no_image': 'SIN IMAGEN - ALERTA',
    'map.search_result': 'Resultado de búsqueda',
    'map.no_reports_found': 'No se encontraron reportes',
    'map.no_my_reports_found': 'Todavía no tenés reportes',
    'map.no_my_reports_cta': 'Creá tu primer reporte con el botón "Sensor Activo".',
    'community.volunteers_in': 'Voluntarios en {zone}',
    'community.no_volunteers': '¡Todavía no hay EcoWarriors en esta zona!',
    'community.active_squads': 'Cuadrillas Activas',
    'community.participants': 'Participantes',
    'community.critical_alert': 'ALERTA CRÍTICA',
    'community.risk_status': 'Estado: Riesgo de Inundación • Acción Inmediata',
    'community.emergency_btn': 'EMERGENCIA',
    'community.explore_title': 'Explorá la App',
    'community.explore_desc': 'Tu centro de comando hídrico',
    'community.map_label': 'Mapa',
    'community.map_desc': 'Visualizá focos de contaminación y zonas de riesgo.',
    'community.report_label': 'Reportar',
    'community.report_desc': 'Cargá un nuevo caso con IA para prevenir desbordes.',
    'community.community_label': 'Comunidad',
    'community.community_desc': 'Conectá con vecinos para organizar limpiezas.',
    'community.profile_label': 'Perfil',
    'community.profile_desc': 'Seguí tu impacto y subí de nivel como Guardián.',
    'community.go_now': 'Ir ahora',
    'community.rocco_missions': 'Misiones de Rocco IA',
    'community.rocco_desc': 'Acciones directas para hoy',
    'community.context_active': 'Contexto: Despejado • Red Activa',
    'community.view_detail': 'Ver Detalle',
    'community.view_all_missions': 'Ver todas las misiones ({count})',
    'community.view_less': 'Ver menos',
    'community.real_impact': 'Impacto Real',
    'community.collective_resilience': 'Resiliencia Colectiva • Última Semana',
    'community.resolved_spots': 'Focos Resueltos',
    'community.resolved_desc_singular': 'Has ayudado a resolver 1 punto crítico en tu barrio.',
    'community.resolved_desc_plural': 'Han ayudado a resolver {count} puntos críticos en el barrio.',
    'community.resolved_desc': '{count} problema{plural} resuelto{plural} por la comunidad.',
    'community.active_reports': 'Reportes Activos',
    'community.active_reports_desc': 'En seguimiento por la comunidad ahora mismo.',
    'community.no_waste_data': 'Sin datos de residuos',
    'community.volunteer_reg': 'Registro de Voluntarios',
    'community.volunteer_desc': 'Tu solidaridad es nuestra mayor fuerza. Únete a nuestra red de reserva para ayudar en futuras acciones comunitarias.',
    'community.want_to_help': 'Quiero Ayudar',
    'community.already_volunteer': '¡Ya eres voluntario!',
    'community.verifying': 'Verificando...',
    'community.marketplace_title': 'Te doy / Recibo',
    'community.marketplace_desc': 'Es el espacio comunitario de EcoWarriors para intercambiar recursos entre vecinos. Podés publicar cosas que querés dar (ropa, herramientas, alimentos) o pedir cosas que necesitás recibir. Todo gratuito, todo entre vecinos del barrio.',
    'community.marketplace_offer_desc': '🎁 Te doy → lo que querés donar',
    'community.marketplace_need_desc': '🙋 Recibo → lo que necesitás',
    'community.no_posts': 'No hay publicaciones aún',
    'community.no_posts_desc': 'Sé el primero en compartir algo con tus vecinos.',
    'community.active_neighbor': 'Vecino Activo',
    'community.details': 'Detalles',
    'community.offer': 'Doy',
    'community.need': 'Necesito',
    'dashboard.hero_tag': 'Novedad',
    'dashboard.hero_title': 'HOY TU BARRIO TE NECESITA',
    'dashboard.hero_desc': 'Cada reporte ayuda a prevenir riesgos y cuidar a la comunidad.',
    'dashboard.cycle_title': 'El ciclo de EcoWarriors',
    'dashboard.cycle_desc': '4 etapas para transformar tu barrio y cuidar a los vecinos.',
    'dashboard.resources_title': 'Recursos y Presentaciones',
    'dashboard.resources_desc': 'Conocé más sobre el proyecto y la tecnología que lo hace posible.',
    'dashboard.view_presentation': 'Ver presentación',
    'dashboard.technical_video': 'Video técnico',
    'dashboard.contact_title': '¿Tenés alguna duda?',
    'dashboard.contact_desc': 'Escribinos y te respondemos a la brevedad.',
    'dashboard.contact_label': 'equipoecowarriors@gmail.com',
    'dashboard.no_reports_found': 'No se encontraron reportes',
    'dashboard.no_reports_desc': 'Intenta ajustar los filtros o la búsqueda para encontrar lo que buscas.',
    'dashboard.delete_confirm': '¿Eliminar este reporte permanentemente?',
    'dashboard.cancel_confirm': '¿Cancelar este reporte? Se marcará como cargado por error.',
    'dashboard.delete_error': 'No se pudo eliminar el reporte. Intentá de nuevo.',
    'dashboard.cancel_error': 'No se pudo cancelar el reporte. Intentá de nuevo.',
    'dashboard.post_delete_confirm': '¿Eliminar este post permanentemente?',
    'dashboard.post_cancel_confirm': '¿Retirar tu publicación? Se marcará como vencida.',
    'dashboard.weather_clear': 'Despejado',
    'dashboard.weather_mostly_clear': 'Mayormente despejado',
    'dashboard.weather_partly_cloudy': 'Parcialmente nublado',
    'dashboard.weather_cloudy': 'Nublado',
    'dashboard.weather_fog': 'Niebla',
    'dashboard.weather_frost_fog': 'Niebla con escarcha',
    'dashboard.weather_light_drizzle': 'Llovizna ligera',
    'dashboard.weather_moderate_drizzle': 'Llovizna moderada',
    'dashboard.weather_dense_drizzle': 'Llovizna densa',
    'dashboard.weather_light_rain': 'Lluvia ligera',
    'dashboard.weather_moderate_rain': 'Lluvia moderada',
    'dashboard.weather_heavy_rain': 'Lluvia fuerte',
    'dashboard.weather_light_snow': 'Nieve ligera',
    'dashboard.weather_moderate_snow': 'Nieve moderada',
    'dashboard.weather_heavy_snow': 'Nieve fuerte',
    'dashboard.weather_light_showers': 'Chubascos ligeros',
    'dashboard.weather_moderate_showers': 'Chubascos moderados',
    'dashboard.weather_violent_showers': 'Chubascos violentos',
    'dashboard.weather_thunderstorm': 'Tormenta eléctrica',
    'dashboard.weather_light_hail_storm': 'Tormenta con granizo ligero',
    'dashboard.weather_heavy_hail_storm': 'Tormenta con granizo fuerte',
    'dashboard.weather_unknown': 'Desconocido',
    'crisis.default_meeting_place': 'Escuela Primaria N° 12',
    'crisis.default_contact_1_name': 'Mamá',
    'crisis.default_contact_2_name': 'Juan (Vecino)',
    'crisis.browser_no_gps': 'Tu navegador no soporta geolocalización.',
    'crisis.location_error_perms': 'No se pudo obtener la ubicación. Por favor, otorga permisos.',
    'crisis.wait_location_error': 'Por favor esperá a que se detecte tu ubicación o ingresá coordenadas válidas antes de continuar.',
    'crisis.manual_location_prefix': 'Ubicación Manual',
    'crisis.gps_location_prefix': 'Ubicación GPS',
    'crisis.default_report_title': 'Reporte de Crisis',
    'crisis.default_report_desc': 'Incidente de tipo {type} reportado en la zona {zone}.',
    'crisis.zone_not_specified': 'no especificada',
    'crisis.contact_name_placeholder': 'Ej: Mamá o Juan',
    'crisis.contact_phone_placeholder': 'Ej: 5491123456789',
    'crisis.emergency_label': 'Emergencias',
    'crisis.latitude_placeholder': 'Latitud',
    'crisis.longitude_placeholder': 'Longitud',
    'crisis.safe_place_defined': 'Lugar Seguro Definido',
    'crisis.done': 'LISTO',
    'crisis.place_name_placeholder': 'Nombre del lugar',
    'crisis.change_place': 'CAMBIAR LUGAR',
    'crisis.emergency_contacts': 'Contactos de Emergencia',
    'crisis.edit': 'Editar',
    'crisis.name_placeholder': 'Nombre',
    'crisis.phone_placeholder': 'Teléfono',
    'crisis.cancel': 'CANCELAR',
    'crisis.update': 'ACTUALIZAR',
    'crisis.save': 'GUARDAR',
    'crisis.cut_guide': 'Guía de Corte',
    'crisis.cut_guide_desc': 'Sigue estas instrucciones para minimizar riesgos en tu hogar.',
    'crisis.step_x_of_y': 'Paso {step} de {total}',
    'crisis.previous': 'ANTERIOR',
    'crisis.next': 'SIGUIENTE',
    'crisis.system_reminders_on': 'SISTEMA: Recordatorios preventivos programados cada 4 horas.',
    'crisis.system_reminders_off': 'SISTEMA: Recordatorios preventivos desactivados.',
    'crisis.calling_911': 'Llamando al 911...',
    'crisis.desktop_call_hint': 'Función de llamada directa disponible solo en móviles',
    'landing.team_role_vision': 'Visión y Estrategia',
    'landing.team_bio_vision': 'Impulsa la visión del proyecto y transforma ideas en acciones concretas con impacto real.',
    'landing.team_role_leadership': 'Liderazgo y Gestión',
    'landing.team_bio_leadership': 'Organiza y lidera el equipo, asegurando que todo funcione y avance con propósito.',
    'landing.team_role_community': 'Desarrollo Comunitario',
    'landing.team_bio_community': 'Conecta a la comunidad y genera espacios donde las personas se involucran y participan.',
    'landing.team_role_edu': 'Comunicación y Educación',
    'landing.team_bio_edu': 'Comunica, educa y convierte la conciencia ambiental en acción.',
    'landing.team_role_analysis': 'Análisis Ambiental',
    'landing.team_bio_analysis': 'Apasionada por el cuidado del agua, analiza y busca soluciones para prevenir problemáticas ambientales.',
    'landing.ods_3_title': 'Salud y Bienestar',
    'landing.ods_3_desc': 'Prevenimos focos de contaminación y enfermedades vectoriales.',
    'landing.ods_6_title': 'Agua Limpia',
    'landing.ods_6_desc': 'Evitamos que los residuos lleguen al agua y contaminen las napas.',
    'landing.ods_11_title': 'Ciudades Sostenibles',
    'landing.ods_11_desc': 'Mejoramos la participación ciudadana y la gestión urbana.',
    'landing.ods_13_title': 'Acción Climática',
    'landing.ods_13_desc': 'Preparamos a la comunidad para responder ante eventos extremos.',
    'landing.years_old': 'años',
    'landing.ods_label': 'ODS',
    'reports.timeline_title': 'Historial de Evolución',
    'reports.add_update': 'Agregar actualización',
    'reports.mark_resolved': 'Marcar como resuelto',
    'reports.report_aggravation': 'Reportar agravamiento',
    'reports.recent_update': 'Reciente',
    'reports.initial_report': 'Reporte Inicial',
    'reports.start_node': 'Inicio',
    'reports.update_title': 'Actualizar',
    'reports.new_status_label': 'Nuevo Estado',
    'reports.change_desc_label': 'Descripción del Cambio',
    'reports.change_desc_placeholder': '¿Qué cambió? ¿Qué acciones se tomaron?',
    'reports.new_evidence_label': 'Nueva Evidencia (Opcional)',
    'reports.upload_evidence_placeholder': 'Subir Foto de Evidencia',
    'reports.confirm_btn': 'Confirmar',
    'reports.saving': 'Guardando...',
    'reports.update_error': 'Error al agregar la actualización. Inténtalo de nuevo.',
    'dashboard.admin': 'Administrador',
    'dashboard.guardian': 'Guardián',
    'profile.xp_points': 'Puntos XP',
    'profile.xp_to_next': 'Faltan {xp} XP para el Nivel {level}',
    'profile.achievements': 'Logros',
    'profile.no_achievements': '¡Aún no tienes logros! Seguí participando.',
    'profile.view_all_count': 'Ver todas las misiones ({count})',
    'reports.unknown_error': 'Error desconocido',
    'reports.approximate_location': 'Ubicación aproximada',
    'community.status_all': 'Todos',
    'community.status_available': 'Disponible',
    'community.status_reserved': 'Reservado',
    'community.status_expired': 'Vencido',
    'community.status_delivered': 'Entregado/Resuelto',
    'community.delete_post_admin': 'Eliminar post (admin)',
    'community.withdraw_post': 'Retirar mi publicación',
    'community.no_description': 'Sin descripción adicional.',
    'dashboard.crisis_desc': 'Acceso rápido a guías de corte de servicios, contactos de emergencia y punto de encuentro vecinal. Activalo cuando necesitás actuar rápido.',
    'dashboard.default_alias': 'EcoWarrior',
    'dashboard.commitment_default': 'Comprometido con el barrio',
    'dashboard.start_now': 'EMPEZAR AHORA',
    'dashboard.preparation': 'En preparación',
    'dashboard.weather_in_caba': 'Clima en CABA',
    'dashboard.instagram_follow': 'Seguinos en Instagram',
    'dashboard.rocco_tip_desc': 'El mejor residuo es el que no se genera. Antes de comprar, pensá si realmente lo necesitás.',
    'dashboard.prevention': 'Prevención',
    'dashboard.prevention_desc': 'Identificar riesgos antes de que ocurran',
    'dashboard.alert': 'Alerta',
    'dashboard.alert_desc': 'Notificar a la comunidad a tiempo',
    'dashboard.action': 'Acción',
    'dashboard.action_desc': 'Actuar colectivamente sobre el problema',
    'dashboard.recovery': 'Recuperación',
    'dashboard.recovery_desc': 'Restablecer la normalidad en el barrio',
    'carousel.hero_tag': 'Novedad',
    'carousel.hero_title': 'HOY TU BARRIO TE NECESITA',
    'carousel.hero_desc': 'Cada reporte ayuda a prevenir riesgos y cuidar a la comunidad.',
    'carousel.cycle_title': 'El ciclo de EcoWarriors',
    'carousel.cycle_desc': '4 etapas para transformar tu barrio y cuidar a los vecinos.',
    'carousel.resources_title': 'Recursos y Presentaciones',
    'carousel.resources_desc': 'Conocé más sobre el proyecto y la tecnología que lo hace posible.',
    'carousel.video_presentation': 'Ver presentación',
    'carousel.video_technical': 'Video técnico',
    'carousel.contact_title': '¿Tenés alguna duda?',
    'carousel.contact_desc': 'Escribinos y te respondemos a la brevedad.',
    'auth.login_title': 'Bienvenido de nuevo',
    'auth.signup_title': 'Unite a la red',
    'auth.forgot_title': 'Recuperar acceso',
    'auth.login_subtitle': 'Tu barrio te estaba esperando.',
    'auth.signup_subtitle': 'Convertite en un sensor activo de tu comunidad.',
    'auth.forgot_subtitle': 'Te enviaremos un link para restablecer tu contraseña.',
    'auth.alias_label': 'Alias de Agente',
    'auth.alias_placeholder': 'Ej: GuardianVerde',
    'auth.zone_label': 'Zona / Comuna',
    'auth.zone_placeholder': 'Ej: Comuna 4',
    'auth.commitment_label': 'Tu Compromiso',
    'auth.commitment_placeholder': 'Ej: Limpiar mi cuadra',
    'auth.email_label': 'Correo Electrónico',
    'auth.email_placeholder': 'agente@ecowarriors.com',
    'auth.password_label': 'Contraseña',
    'auth.confirm_password_label': 'Confirmar',
    'auth.forgot_password_link': '¿Olvidaste tu contraseña?',
    'auth.or_continue': 'O también',
    'auth.google_continue': 'Continuar con Google',
    'auth.google_reset_hint': 'Si te registraste con Google, no necesitas restablecer contraseña. Simplemente usa el botón "Continuar con Google".',
    'auth.google_account_detected': 'Cuenta de Google detectada',
    'auth.login_google': 'Iniciar sesión con Google',
    'auth.reset_instructions': 'Ingresá tu email para recibir un link de recuperación.',
    'auth.have_account': '¿Ya sos un EcoWarrior? Iniciá sesión',
    'auth.no_account': '¿No tenés cuenta? Unite a la red',
    'auth.back_to_login': 'Volver al inicio de sesión',
    'auth.create_account': 'Crear Cuenta',
    'auth.send_link': 'Enviar Link',
    'auth.login_button': 'Iniciar Sesión',
    'auth.error_email_required': 'El correo electrónico es obligatorio',
    'auth.error_alias_required': 'El alias de agente es obligatorio',
    'auth.error_password_min': 'La contraseña debe tener al menos 6 caracteres',
    'auth.error_password_mismatch': 'Las contraseñas no coinciden',
    'auth.error_zone_required': 'La zona de responsabilidad es obligatoria',
    'auth.error_password_required': 'La contraseña es obligatoria',
    'auth.error_unexpected': 'Ocurrió un error inesperado',
    'auth.error_email_in_use': 'Este correo ya está registrado',
    'auth.error_invalid_email': 'Correo electrónico inválido',
    'auth.error_invalid_credentials': 'Credenciales incorrectas',
    'auth.error_too_many_requests': 'Demasiados intentos. Reintenta más tarde.',
    'auth.success_reset_sent': 'Se ha enviado un enlace de recuperación a tu correo.',
    'auth.error_google_unauthorized': 'Este dominio no está autorizado en Firebase. Contactá al administrador.',
    'auth.error_google_popup_blocked': 'El navegador bloqueó el popup. Permití los popups para este sitio e intentá de nuevo.',
    'auth.error_google_popup_closed': 'Cerraste la ventana de Google antes de completar el proceso.',
    'auth.error_google_cancelled': 'Operación cancelada. Intentá de nuevo.',
    'auth.error_user_not_found': 'No encontramos una cuenta con ese email.',
    'auth.error_invalid_email_format': 'El formato del email no es válido.',
    'auth.error_reset_failed': 'No se pudo enviar el correo de recuperación. Intentá de nuevo.',
    'auth.resend_in': 'Reenviar en',
    'dashboard.flood_risk': '⚠️ Riesgo de inundación',
    'reports.image_mismatch': 'La imagen no coincide con la descripción.',
    'reports.ia_unclear': 'IA incierta. Sube una foto más clara.',
    'reports.error_no_image': 'Debes subir al menos una imagen.',
    'reports.geo_not_supported': 'Geolocalización no compatible.',
    'reports.ai_key_missing': 'Error de configuración: La clave de IA no está configurada.',
    'reports.ai_processing_error': 'La IA no pudo procesar la imagen. Intentá con otra foto.',
    'reports.db_save_error': 'Error al guardar el reporte en la base de datos.',
    'reports.analyze_error': 'Error al analizar el reporte. Por favor, intentá de nuevo.',
    'reports.analysis_error': 'No pudimos analizar el reporte automáticamente. Por favor, intenta describirlo con más detalle.',
    'reports.edit_data': 'Editar Datos',
    'community.volunteer_network': 'Unite a la Red de Voluntarios de Emergencia',
    'validation.phone_invalid': 'Ingresá un número de teléfono válido (ej: +5491123456789)',
    'validation.name_invalid': 'El nombre debe tener entre 2 y 40 caracteres',
    'validation.description_min': 'La descripción debe tener al menos 10 caracteres',
    'validation.title_invalid': 'El título debe tener entre 5 y 100 caracteres',
    'validation.coordinate_invalid': 'Coordenada inválida',
  },
  en: {
    'common.by': 'By',
    'common.ecowarrior': 'EcoWarrior',
    'common.admin': 'Administrator',
    'community.squad_status_upcoming': 'Upcoming',
    'community.squad_status_finished': 'Finished',
    'community.squad_status_cancelled': 'Cancelled',
    'community.squad_time_label': 'Time',
    'community.squad_desc_placeholder': 'What will be done? What tools should people bring?',
    'community.squad_location_placeholder': 'e.g., Central Park, Main St 100',
    'community.squad_max_participants_label': 'Max. Participants (0 for unlimited)',
    'community.squad_save_button': 'SAVE SQUAD',
    'community.squad_creating_button': 'CREATING...',
    'community.squad_save_changes': 'SAVE CHANGES',
    'community.squad_create_btn': 'CREATE SQUAD',
    'community.squad_edit_title': 'Edit Squad',
    'community.squad_create_title': 'Create New Squad',
    'community.squad_title_label': 'Action Title',
    'community.squad_title_placeholder': 'e.g., North Drain Cleaning',
    'community.squad_attendees_title': 'Squad Attendees',
    'community.people_joined': 'people have joined',
    'community.squad_attendees': 'Attendees',
    'community.squad_leave': 'Leave Squad',
    'community.squad_join': 'Join Squad',
    'community.cancel_squad_title': 'Cancel Squad',
    'community.cancel_squad_confirm': 'Are you sure you want to cancel this squad? Attendees will be notified.',
    'nav.dashboard': 'Dashboard',
    'nav.reports': 'Reports',
    'nav.community': 'Community',
    'nav.map': 'Map',
    'nav.chatbot': 'Rocco AI',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.crisis_mode': 'Crisis Mode',
    'feedback.button': 'Feedback',
    'feedback.title': 'We want to hear your opinion',
    'feedback.description': 'Your feedback helps us improve EcoWarriors and generate a greater impact in the community.',
    'feedback.respond_form': 'Answer form',
    'feedback.respond_form_new_tab': 'Answer form (opens in a new tab)',
    'nav.resilience': 'Citizen Resilience',
    'landing.login': 'Log in',
    'landing.signup': 'Create account',
    'landing.hero_badge': 'Urban Resilience Network',
    'landing.hero_title_1': 'Trash doesn\'t just',
    'landing.hero_title_2': 'dirty',
    'landing.hero_title_3': 'floods',
    'landing.hero_subtitle': 'Become an active sensor for your neighborhood and help us prevent water disasters.',
    'landing.about_title': 'Who We Are',
    'landing.about_subtitle': 'A team committed to transforming our cities through technology and community action.',
    'landing.impact_title': 'Your Impact',
    'landing.impact_subtitle': 'Every report and action contributes directly to the UN Sustainable Development Goals.',
    'landing.edu_title': 'Did you know a clogged drain multiplies the risk of flooding?',
    'landing.edu_desc': 'Waste thrown on public roads ends up in the drains, reducing their drainage capacity by 70%. Your early report allows for preventive cleaning before the storm.',
    'landing.stat_obstruction': 'Obstruction',
    'landing.stat_obstruction_desc': 'of lost capacity',
    'landing.stat_prevention': 'Prevention',
    'landing.stat_prevention_desc': 'before the rain',
    'landing.stat_impact': 'Impact',
    'landing.stat_impact_desc': 'less material damage',
    'landing.support_thanks_title': 'Thanks to those who gave us space to share our idea and help it grow',
    'landing.support_thanks_subtitle': 'These spaces, institutions, and companies supported our path to turn environmental awareness into community action.',
    'landing.support_gallery_title': 'Project gallery',
    'landing.support_gallery_subtitle': 'Real moments of our team presenting EcoWarriors and building networks for greater impact.',
    'landing.security_title': 'Security Commitment',
    'landing.security_subtitle': 'Your safety is our number one priority.',
    'landing.security_rule_1': 'Never approach areas of imminent danger or fallen wires.',
    'landing.security_rule_2': 'Use the application only from safe and stable places.',
    'landing.security_rule_3': 'In case of a real emergency, always call 911 first.',
    'landing.security_accept': 'I understand and accept the safety rules',
    'landing.directory_title': 'Useful Directory',
    'landing.directory_subtitle': 'Quick access to emergency numbers and essential public services in your area.',
    'landing.directory_emergencies': 'Emergencies',
    'landing.directory_civil_defense': 'Civil Defense',
    'landing.directory_firefighters': 'Firefighters',
    'landing.ready_title': 'Ready to start?',
    'landing.ready_desc': 'Join Sarah, Brune, Agus, Delfi, Martu and hundreds of neighbors who are already taking care of their neighborhood.',
    'landing.start_now': 'START NOW',
    'landing.security_warning': 'You must accept the safety rules to continue',
    'landing.footer_copy': '© 2026 EcoWarriors. Made with love for the planet.',
    'reports.filter_open': 'Open',
    'reports.filter_resolved': 'Resolved',
    'reports.filter_mine': 'Mine',
    'reports.title_all': 'All Reports',
    'reports.title_mine': 'My Reports',
    'reports.desc_all': 'Explore the community environmental situation',
    'reports.desc_mine': 'Manage your environmental contributions',
    'reports.new_report': 'New Report',
    'reports.search_placeholder': 'Search reports...',
    'reports.cancelled': '(Cancelled)',
    'community.no_events': 'No upcoming events',
    'community.enrolled': 'Enrolled',
    'community.join_squad': 'Join the Squad',
    'community.what_is_squad': 'What is a squad?',
    'community.squad_desc': 'They are groups of neighbors organized for quick actions: cleaning drains, removing debris, or post-storm logistical help.',
    'marketplace.title': 'Solidarity Marketplace',
    'marketplace.desc': 'Exchange of resources and tools between neighbors',
    'marketplace.banner_title': 'How does the Marketplace work?',
    'marketplace.banner_desc': 'Post tools you no longer use or ask for what you need to improve your area. We promote circular economy and mutual aid.',
    'marketplace.banner_button': 'Got it',
    'marketplace.filter_all': 'All',
    'marketplace.filter_available': 'Available',
    'marketplace.filter_reserved': 'Reserved',
    'marketplace.filter_expired': 'Expired',
    'marketplace.search_placeholder': 'Search the marketplace...',
    'marketplace.no_posts': 'No posts found',
    'marketplace.no_posts_desc': 'Try other filters or search terms',
    'marketplace.offer': 'OFFER',
    'marketplace.need': 'NEED',
    'marketplace.active_neighbor': 'Active Neighbor',
    'marketplace.details': 'Details',
    'community.title': 'COMMUNITY',
    'community.squads': 'Squads',
    'community.no_squads': 'No squads scheduled yet.',
    'community.active_warriors': 'EcoWarriors active in your area.',
    'community.be_first': 'Be the first in your area to report.',
    'community.scheduled_crews': 'A scheduled squad is coming soon.',
    'community.scheduled_crews_plural': 'Scheduled squads are coming soon.',
    'mission.reward_label': 'XP',
    'mission.status_in_progress': 'In progress',
    'mission.status_available': 'Available',
    'mission.description': 'Description',
    'mission.objective': 'Objective',
    'mission.suggested_action': 'Suggested action',
    'mission.close': 'Close',
    'mission.title_primer-reporte': 'First Report',
    'mission.desc_primer-reporte': 'Create a report with an image',
    'mission.obj_primer-reporte': 'Visually document an environmental problem to facilitate its identification.',
    'mission.action_primer-reporte': 'Look for a problem in your area, take a photo and report it.',
    'mission.title_ojo-aguila': 'Eagle Eye',
    'mission.desc_ojo-aguila': 'Report an area not previously reported',
    'mission.obj_ojo-aguila': 'Expand EcoWarriors map coverage to new areas.',
    'mission.action_ojo-aguila': 'Explore an area of the map that has no active reports and create one.',
    'mission.title_ojo-critico': 'Critical Eye',
    'mission.desc_ojo-critico': 'Add an update to an existing report',
    'mission.obj_ojo-critico': 'Keep information updated for better follow-up.',
    'mission.action_ojo-critico': 'Look for a nearby report and add a comment or photo about its current status.',
    'mission.title_cierre-responsable': 'Responsible Closure',
    'mission.desc_cierre-responsable': 'Mark a report as resolved with evidence',
    'mission.obj_cierre-responsable': 'Confirm problem resolution with visual proof.',
    'mission.action_cierre-responsable': 'When you see a problem is fixed, update it to \"Resolved\" by uploading a photo.',
    'mission.title_accion-comunitaria': 'Community Action',
    'mission.desc_accion-comunitaria': 'Sign up for a squad',
    'mission.obj_accion-comunitaria': 'Encourage participation in high-impact group activities.',
    'mission.action_accion-comunitaria': 'Join one of the active squads in the Community tab.',
    'mission.title_prevencion-activa': 'Active Prevention',
    'mission.desc_prevencion-activa': 'Set up a contact and use Crisis Mode',
    'mission.obj_prevencion-activa': 'Be prepared for emergency situations.',
    'mission.action_prevencion-activa': 'Complete the Crisis Mode onboarding and set up your trusted contacts.',
    'achievement.title_first-report': 'First Report',
    'achievement.desc_first-report': 'You documented your first environmental problem.',
    'achievement.title_problem-solver': 'Problem Solver',
    'achievement.desc_problem-solver': 'You helped resolve at least one report.',
    'achievement.title_community-hero': 'Community Hero',
    'achievement.desc_community-hero': 'You participated in your first squad.',
    'achievement.title_active-guardian': 'Active Guardian',
    'achievement.title_crisis-responder': 'Crisis Responder',
    'achievement.title_squad-leader': 'Squad Leader',
    'achievement.title_environmental-expert': 'Environmental Expert',
    'achievement.desc_active-guardian': 'You made more than 5 reports.',
    'community.weather_current': 'Current weather',
    'community.weather_loading': 'Loading weather data...',
    'profile.title': 'EcoWarrior Profile',
    'profile.reports': 'Reports',
    'profile.resolved': 'Resolved',
    'profile.xp': 'XP Points',
    'profile.level': 'Level',
    'profile.zone': 'Zone',
    'profile.commitment': 'Commitment',
    'profile.missions': "Rocco's Missions",
    'profile.ranking': 'Ranking',
    'profile.my_reports': 'My Reports',
    'profile.settings': 'Settings',
    'profile.notifications': 'Notifications',
    'profile.language': 'Language',
    'profile.privacy': 'Privacy',
    'profile.privacy_exact': 'Exact location',
    'profile.privacy_exact_desc': 'Other users will see your exact location for a faster response.',
    'profile.privacy_approximate': 'Approximate zone',
    'profile.privacy_approximate_desc': 'Only a general area will be shown to protect your privacy.',
    'profile.privacy_modal_title': 'Location Privacy',
    'profile.privacy_modal_desc': 'Choose how you want your location to be displayed in reports.',
    'profile.logout': 'Logout',
    'profile.view_all_count': 'View all missions ({count})',
    'profile.view_less': 'View less',
    'profile.active': 'Active',
    'profile.inactive': 'Inactive',
    'reports.mine': 'My Reports',
    'reports.all': 'Active Reports',
    'reports.mine_desc': 'Your contributions to the resilience network',
    'reports.all_desc': 'Monitoring of environmental incidents and crises',
    'reports.filter_all': 'All',
    'reports.search': 'Search reports...',
    'reports.empty_mine': "You don't have reports yet",
    'reports.empty_all': 'No active reports',
    'dashboard.weather_in': 'Weather in',
    'dashboard.default_zone': 'Default zone',
    'dashboard.rocco_tip_title': "Rocco's Tip",
    'weather.partly_cloudy': 'Partly cloudy',
    'onboarding.zone_placeholder': 'Your zone or neighborhood',
    'reports.environmental': 'Environmental',
    'reports.crisis': 'Crisis',
    'reports.title_label': 'Report Title',
    'reports.title_placeholder': 'e.g., Trash on the corner',
    'reports.description_label': 'Description',
    'reports.description_placeholder': 'Describe the problem in detail...',
    'reports.visual_evidence': 'Visual Evidence',
    'reports.location_label': 'Location',
    'reports.location_not_detected': 'Location not detected',
    'reports.analyze_button': 'Analyze with AI',
    'reports.upload_photo': 'Upload Photo',
    'reports.getting_gps': 'Getting GPS...',
    'reports.geolocation_not_supported': 'Geolocation not supported.',
    'reports.coords_label': 'Coordinates',
    'reports.location_error': 'Location error',
    'reports.wait_location': 'Waiting for location...',
    'reports.fill_all_fields': 'Please fill in all fields.',
    'reports.analyzing': 'Analyzing...',
    'reports.ai_analysis': 'AI Analysis',
    'reports.suggested_category': 'Suggested category',
    'reports.urgency_level': 'Urgency level',
    'reports.urgency_value': 'Level {level}',
    'reports.correct_data': 'Is the data correct?',
    'reports.confirm_publish': 'Confirm and Publish',
    'map.search_placeholder': 'Search location or place...',
    'reports.empty_all_desc': 'Be the first to report an incident in your area to help the community.',
    'reports.crisis_alert': 'CRISIS ALERT: No evidence image',
    'reports.manual_coords': 'Manual Coordinates',
    'reports.optional': 'Optional',
    'reports.resolved': 'Resolved',
    'common.ecowarriors': 'EcoWarriors',
    'common.ai_verified': 'AI Verified',
    'common.xp_points': 'XP Points',
    'common.info': 'Information',
    'common.voice_input': 'Voice input',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.success': 'Success',
    'weather.clear': 'Clear',
    'reports.no_coords': 'No coordinates',
    'landing.light_mode': 'Light Mode',
    'landing.dark_mode': 'Dark Mode',
    'common.view_in_profile': 'View in my Profile',
    'community.volunteer_signup': 'Volunteer Registration',
    'community.volunteer_signup_desc': 'By registering, you join our contact network for emergency actions or scheduled cleanups. Your data is private and will only be used to coordinate help.',
    'community.volunteer_name_label': 'Name or Alias',
    'community.volunteer_name_placeholder': 'How should we call you?',
    'community.volunteer_contact_label': 'Direct Contact',
    'community.volunteer_contact_placeholder': 'WhatsApp or Email',
    'community.volunteer_help_label': 'How can you help? (Optional)',
    'community.volunteer_help_placeholder': 'e.g., I have a truck, I know logistics, heavy cleaning...',
    'community.volunteer_confirm': 'CONFIRM REGISTRATION',
    'community.post_type_offer': 'New Donation (Offer)',
    'community.post_type_need': 'Request Help (Need)',
    'community.post_photos_label': 'Photos (1-5)',
    'community.post_title_label': 'Title',
    'community.post_title_placeholder': 'e.g., Warm clothes, Food...',
    'community.post_tag_label': 'Tag',
    'community.post_details_label': 'Details',
    'community.post_details_placeholder': 'Add relevant information...',
    'community.post_contact_label': 'Contact',
    'community.post_contact_placeholder': 'WhatsApp or Social Media...',
    'community.post_publish': 'PUBLISH',
    'community.squad_event': 'Squad Event',
    'community.tag_ropa': 'Clothing',
    'community.tag_comida': 'Food',
    'community.tag_otros': 'Others',
    'community.date_label': 'Date',
    'community.location_label': 'Location',
    'community.description_label': 'Description',
    'community.participants_label': 'Participants',
    'community.neighbors_label': 'Neighbors',
    'community.im_attending': 'I will attend!',
    'community.join_button': 'Join',
    'community.manage_status': 'Manage Status',
    'crisis.manual_coords': 'Manual Coordinates',
    'crisis.gps_location': 'GPS Location',
    'crisis.use_gps': 'Use GPS',
    'crisis.enter_manually': 'Enter manually',
    'crisis.coords_required': 'Coordinates are required',
    'crisis.urgency_high': 'High',
    'crisis.urgency_critical': 'Critical',
    'crisis.sending': 'Sending...',
    'crisis.send_report': 'Send Report',
    'crisis.upload_damage_photo': 'Upload damage photo',
    'crisis.damage_type': 'Damage Type',
    'crisis.select_damage': 'Select damage type',
    'crisis.roof_damage': 'Roof damage',
    'crisis.house_collapse': 'House collapse',
    'crisis.severe_flood': 'Severe flood',
    'crisis.other_damage': 'Other damage',
    'reports.status_all': 'All statuses',
    'reports.status_pending': 'Pending',
    'reports.status_verified': 'Verified',
    'reports.status_resolved': 'Resolved',
    'profile.recent_reports': 'My Recent Reports',
    'profile.view_all': 'View all',
    'profile.manage_reports': 'Manage Reports',
    'profile.manage_reports_desc': 'Detailed tracking of your alerts',
    'profile.ranking_title': 'Ranking',
    'profile.top_agents': 'Top 5 Agents',
    'profile.xp_accumulated': 'XP accumulated',
    'profile.dark_mode': 'Dark Mode',
    'error.profile_not_found': 'User profile could not be found.',
    'error.server_connection': 'Error connecting to the server.',
    'common.close': 'Close',
    'common.description': 'Description',
    'common.objective': 'Objective',
    'common.completed': 'Completed',
    'common.in_progress': 'In progress',
    'common.rocco_suggestion': "Rocco's Suggestion",
    'common.active_sensor': 'Active Sensor',
    'common.report': 'Report',
    'common.volunteer_signup': 'Volunteer Signup',
    'dashboard.start_now': 'START NOW',
    'dashboard.preparation': 'In preparation',
    'dashboard.weather_in_caba': 'Weather in CABA',
    'dashboard.instagram_follow': 'Follow us on Instagram',
    'dashboard.rocco_tip_desc': "The best waste is the one that's never created. Before buying, think if you really need it.",
    'dashboard.prevention': 'Prevention',
    'dashboard.prevention_desc': 'Identify risks before they happen',
    'dashboard.alert': 'Alert',
    'dashboard.alert_desc': 'Notify the community in time',
    'dashboard.action': 'Action',
    'dashboard.action_desc': 'Act collectively on the problem',
    'dashboard.recovery': 'Recovery',
    'dashboard.recovery_desc': 'Restore normalcy in the neighborhood',
    'crisis.title': 'Crisis Mode',
    'crisis.im_ok': "I'm OK",
    'crisis.im_safe_title': 'ARE YOU SAFE?',
    'crisis.im_safe_desc': 'Send your location and status to your contacts',
    'crisis.sent': 'SENT',
    'crisis.report_damage': 'Report Damage',
    'crisis.meeting_point': 'Meeting Point',
    'crisis.guide': 'Services Guide',
    'crisis.backpack': 'Emergency Kit',
    'crisis.exit': 'Exit Crisis Mode',
    'crisis.finish': 'Finish Crisis',
    'crisis.add_contact': 'Add Trusted Contact',
    'rocco.welcome': 'Hello! I am Rocco, your environmental mentor. How can I help you today?',
    'rocco.suggested_1': 'How to report a problem?',
    'rocco.suggested_2': 'What is a squad?',
    'rocco.suggested_3': 'Recycling tips',
    'rocco.suggested_4': 'Weather status',
    'rocco.mentor_online': 'Environmental Mentor • Online',
    'rocco.reset_chat': 'Reset conversation',
    'rocco.placeholder': 'Type your message here...',
    'rocco.error_connection': 'Oops, it seems my connection to the environmental network failed, try again in a moment.',
    'rocco.error_processing': 'Oops, it seems my connection to the environmental network failed, try again in a moment.',
    'rocco.rate_limit_message': 'You are sending messages too fast. Wait {seconds}s before sending another one.',
    'rocco.system_instruction': 'You are Rocco, the AI assistant of EcoWarriors: Urban Resilience. Your only role is to help users with topics directly related to this application and its context. You can answer about: how to use the app (reports, squads, missions, map, marketplace, crisis mode), urban ecology, environmental pollution, waste management, flood prevention, climate emergencies, circular economy, and urban sustainability. If the user asks something NOT related to these topics (e.g. cooking recipes, sports, politics, entertainment, math, code, etc.), respond with exactly this: "I can only help you with topics related to EcoWarriors and the urban environment. Do you have any questions about the app or neighborhood care?" Do not answer off-topic questions under any circumstances, even if the user insists. Always respond in {lang}.',
    'rocco.missions_title': 'Active Missions',
    'rocco.view_progress': 'View Progress',
    'rocco.all_completed': 'All missions completed!',
    'rocco.no_missions': 'No missions available',
    'rocco.tip_title': 'Eco-Tip of the Day',
    'rocco.tip_desc': 'Did you know that recycling one ton of paper saves 17 trees and 26,000 liters of water?',
    'rocco.tip_help': 'Tell me more about this tip: {tip}',
    'rocco.learn_more': 'Learn more',
    'rocco.mission_help': 'Tell me more about the mission: {title}. {description}',
    'rocco.voice_soon': 'Voice input coming soon',
    'crisis.activate': 'Activate Alert',
    'crisis.preventive_reminders': 'Preventive Reminders',
    'crisis.reminders_desc': 'Water and battery check every 4h',
    'crisis.emergency_call': 'CALL',
    'crisis.back': 'BACK',
    'crisis.edit_contact': 'Edit Contact',
    'crisis.safe_message': "I'M OK. My current location:",
    'crisis.safe_message_no_gps': "I'M OK. (Could not obtain exact location)",
    'crisis.onboarding_title': 'WELCOME TO CRISIS MODE',
    'crisis.onboarding_desc': 'A tool designed to keep you safe during extreme weather events.',
    'crisis.onboarding_contacts_title': 'TRUSTED CONTACTS',
    'crisis.onboarding_contacts_desc': 'Configure who will receive your "I\'m safe" signal with your exact location.',
    'crisis.contact_name_label': 'Contact Name',
    'crisis.contact_phone_label': 'WhatsApp (with country code)',
    'crisis.save_continue': 'SAVE AND CONTINUE',
    'crisis.ready_title': 'ALL READY!',
    'crisis.ready_desc': 'You can now use Crisis Mode. Remember this tool is for emergencies.',
    'crisis.start': 'START',
    'crisis.signal_active': 'Signal: Active',
    'crisis.version': 'EcoWarriors Crisis v1.0',
    'crisis.no_contact_warning': 'Configure a trusted contact to use this feature.',
    'crisis.location_error': 'Error obtaining location',
    'crisis.signal_sent_success': 'Signal sent successfully.',
    'crisis.offline_warning': 'No connection. The signal will be sent when you recover internet.',
    'dashboard.crisis_mode': 'Crisis Mode',
    'dashboard.activate_now': 'Activate now',
    'dashboard.activate_crisis': 'Activate Crisis Mode',
    'dashboard.no_squads': 'No squads scheduled at the moment. Create one from the Community section!',
    'dashboard.view_profile': 'View in my Profile',
    'dashboard.level_progress': 'Level {level} • Rank Progress',
    'dashboard.squad_event': 'Squad Event',
    'community.search_board': 'Search the board...',
    'community.volunteer_zone': 'Neighborhood or Area',
    'reports.urgency_1': 'Level 1: Low',
    'reports.urgency_2': 'Level 2: Informational',
    'reports.urgency_3': 'Level 3: Attention',
    'reports.urgency_4': 'Level 4: Follow-up',
    'reports.urgency_5': 'Level 5: Critical',
    'map.flood_risk': 'Moderate flooding risk zone',
    'map.road_risk': 'High traffic and accident risk zone',
    'map.energy_point': 'Electrical Substation - Operational',
    'map.loading': 'Loading collaborative map...',
    'map.legend_title': 'Report Statuses',
    'map.update_report': 'Update Report',
    'map.early_warning': 'Early Warning System',
    'map.real_time_monitoring': 'Real-time monitoring',
    'common.save_changes': 'Save Changes',
    'common.retry': 'Retry',
    'common.loading': 'Loading...',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.edit_profile': 'Edit Profile',
    'common.username_alias': 'Username / Alias',
    'common.new_alias_placeholder': 'Your new alias...',
    'common.photo_updated': 'Photo updated',
    'common.invalid_image': 'Please select a valid image.',
    'common.upload_error': 'Error uploading photo.',
    'common.profile_not_found': 'Profile not found',
    'common.server_connection_error': 'Server connection error',
    'reports.confirm_report': 'Confirm Report',
    'reports.create_error': 'Error creating report. Try again.',
    'reports.create_success': 'Report created successfully. Thank you for your commitment!',
    'reports.invalid_coords': 'Location must contain valid coordinates (latitude and longitude).',
    'reports.zone': 'Zone',
    'reports.commitment': 'Commitment',
    'reports.undefined': 'Undefined',
    'crisis.report_help_text': 'This report helps prioritize community assistance. If there is an imminent life risk, call 911.',
    'crisis.visual_evidence': 'Visual Evidence (Optional)',
    'crisis.report_success': 'Crisis report sent and reflected on the collaborative map.',
    'crisis.offline_report_success': 'No connection or session. Your crisis report has been saved locally and will be sent when connection is restored.',
    'crisis.electricity_guide': 'Electricity (Light)',
    'crisis.gas_guide': 'Gas',
    'crisis.water_guide': 'Water',
    'crisis.guide_warning': 'Warning',
    'crisis.backpack_cat_food': 'Water and Food',
    'crisis.backpack_item_water': 'Water (2L per person/day)',
    'crisis.backpack_item_food': 'Non-perishable food',
    'crisis.backpack_item_opener': 'Manual can opener',
    'crisis.backpack_item_utensils': 'Basic utensils',
    'crisis.backpack_cat_docs': 'Documentation',
    'crisis.backpack_item_id': 'ID/Passport (physical or copy)',
    'crisis.backpack_item_titles': 'Property titles/Rental',
    'crisis.backpack_item_insurance': 'Medical insurance',
    'crisis.backpack_item_cash': 'Cash',
    'crisis.backpack_cat_health': 'Health and Hygiene',
    'crisis.backpack_item_firstaid': 'First aid kit',
    'crisis.backpack_item_meds': 'Prescription medications',
    'crisis.backpack_item_alcohol': 'Hand sanitizer',
    'crisis.backpack_item_soap': 'Soap and towels',
    'crisis.backpack_cat_tools': 'Shelter and Tools',
    'crisis.backpack_item_blanket': 'Thermal blanket or sleeping bag',
    'crisis.backpack_item_clothes': 'Change of clothes',
    'crisis.backpack_item_flashlight': 'Flashlight and spare batteries',
    'crisis.backpack_item_radio': 'Battery-powered AM/FM radio',
    'crisis.backpack_item_whistle': 'Whistle',
    'crisis.elec_step1': 'Locate the main panel.',
    'crisis.elec_step2': 'Turn off the main thermal switch.',
    'crisis.elec_step3': 'Do not touch the panel if it is wet or there is water around.',
    'crisis.elec_warning': 'Danger of electrocution if there is flooding.',
    'crisis.gas_step1': 'Locate the shut-off valve (near the meter).',
    'crisis.gas_step2': 'Turn the handle 90 degrees (perpendicular position to the pipe).',
    'crisis.gas_step3': 'If you smell gas, do not turn on lights or matches.',
    'crisis.gas_warning': 'Close the gas if leaks or structural damage are suspected.',
    'crisis.water_step1': 'Locate the main shut-off valve.',
    'crisis.water_step2': 'Turn clockwise until it stops.',
    'crisis.water_step3': 'Fill clean containers before shutting it off, if possible.',
    'crisis.water_warning': 'Avoid consuming tap water if contamination is suspected.',
    'reports.status_new': 'Open (new)',
    'reports.status_followup': 'Open (follow-up)',
    'reports.status_aggravated': 'Open (aggravated)',
    'reports.status_cancelled': 'Cancelled',
    'reports.no_image': 'No Image',
    'reports.delete_confirm': 'Delete this report permanently?',
    'reports.cancel_confirm': 'Cancel this report? It will be marked as uploaded by mistake.',
    'reports.delete_admin': 'Delete report (admin)',
    'reports.cancel_mine': 'Cancel my report',
    'reports.details': 'Details',
    'reports.recent': 'Recent',
    'reports.location_unavailable': 'Location unavailable',
    'reports.mode_crisis': 'CRISIS MODE',
    'reports.mode_environmental': 'ENVIRONMENTAL',
    'reports.priority_label': 'Priority',
    'reports.priority_high': 'High',
    'reports.priority_medium': 'Medium',
    'reports.priority_low': 'Low',
    'reports.verifications_label': 'Verifications',
    'reports.verifications_count': '{count} {unit}',
    'reports.neighbor': 'Neighbor',
    'reports.neighbors': 'Neighbors',
    'reports.view_history': 'View Full History',
    'reports.system_status': 'System Status',
    'reports.reported_on': 'Reported on',
    'reports.by': 'By',
    'reports.no_evidence_image': 'No Evidence Image',
    'map.base_layer': 'Base Map',
    'map.citizen_reports': 'Citizen Reports',
    'map.flood_layer': 'Floods / Waterlogging',
    'map.energy_layer': 'Energy Points',
    'map.road_layer': 'Road Risk',
    'map.emergency': 'Emergency',
    'map.alert_no_image': 'NO IMAGE - ALERT',
    'map.search_result': 'Search result',
    'map.no_reports_found': 'No reports found',
    'map.no_my_reports_found': 'You do not have reports yet',
    'map.no_my_reports_cta': 'Create your first report with the "Active Sensor" button.',
    'community.volunteers_in': 'Volunteers in {zone}',
    'community.no_volunteers': 'No EcoWarriors in this area yet!',
    'community.active_squads': 'Active Squads',
    'community.participants': 'Participants',
    'community.critical_alert': 'CRITICAL ALERT',
    'community.risk_status': 'Status: Flood Risk • Immediate Action',
    'community.emergency_btn': 'EMERGENCY',
    'community.explore_title': 'Explore the App',
    'community.explore_desc': 'Your water command center',
    'community.map_label': 'Map',
    'community.map_desc': 'Visualize pollution spots and risk zones.',
    'community.report_label': 'Report',
    'community.report_desc': 'Upload a new case with AI to prevent overflows.',
    'community.community_label': 'Community',
    'community.community_desc': 'Connect with neighbors to organize cleanups.',
    'community.profile_label': 'Profile',
    'community.profile_desc': 'Track your impact and level up as a Guardian.',
    'community.go_now': 'Go now',
    'community.rocco_missions': 'Rocco AI Missions',
    'community.rocco_desc': 'Direct actions for today',
    'community.context_active': 'Context: Clear • Active Network',
    'community.view_detail': 'View Details',
    'community.view_all_missions': 'View all missions ({count})',
    'community.view_less': 'View less',
    'profile.view.less': 'View less',
    'community.real_impact': 'Real Impact',
    'community.collective_resilience': 'Collective Resilience • Last Week',
    'community.resolved_spots': 'Resolved Spots',
    'community.resolved_desc_singular': 'You have helped resolve 1 critical spot in your neighborhood.',
    'community.resolved_desc_plural': 'You have helped resolve {count} critical spots in the neighborhood.',
    'community.resolved_desc': '{count} problem{plural} resolved by the community.',
    'community.active_reports': 'Active Reports',
    'community.active_reports_desc': 'Currently being tracked by the community.',
    'community.no_waste_data': 'No waste data',
    'community.volunteer_reg': 'Volunteer Registration',
    'community.volunteer_desc': 'Your solidarity is our greatest strength. Join our reserve network to help in future community actions.',
    'community.want_to_help': 'I Want to Help',
    'community.already_volunteer': 'You are already a volunteer!',
    'community.verifying': 'Verifying...',
    'community.marketplace_title': 'I give / I receive',
    'community.marketplace_desc': 'EcoWarriors community space to exchange resources between neighbors. You can post things you want to give (clothes, tools, food) or ask for things you need. Everything is free and shared between neighbors.',
    'community.marketplace_offer_desc': '🎁 I give → what you want to donate',
    'community.marketplace_need_desc': '🙋 I receive → what you need',
    'community.no_posts': 'No posts yet',
    'community.no_posts_desc': 'Be the first to share something with your neighbors.',
    'community.active_neighbor': 'Active Neighbor',
    'community.details': 'Details',
    'community.offer': 'I give',
    'community.need': 'I need',
    'dashboard.hero_tag': 'New',
    'dashboard.hero_title': 'YOUR NEIGHBORHOOD NEEDS YOU TODAY',
    'dashboard.hero_desc': 'Every report helps prevent risks and care for the community.',
    'dashboard.cycle_title': 'The EcoWarriors Cycle',
    'dashboard.cycle_desc': '4 stages to transform your neighborhood and care for your neighbors.',
    'dashboard.resources_title': 'Resources and Presentations',
    'dashboard.resources_desc': 'Learn more about the project and the technology that makes it possible.',
    'dashboard.view_presentation': 'View presentation',
    'dashboard.technical_video': 'Technical video',
    'dashboard.contact_title': 'Have any questions?',
    'dashboard.contact_desc': 'Write to us and we will respond shortly.',
    'dashboard.contact_label': 'equipoecowarriors@gmail.com',
    'dashboard.no_reports_found': 'No reports found',
    'dashboard.no_reports_desc': 'Try adjusting the filters or search to find what you are looking for.',
    'dashboard.delete_confirm': 'Delete this report permanently?',
    'dashboard.cancel_confirm': 'Cancel this report? It will be marked as uploaded by mistake.',
    'dashboard.delete_error': 'Could not delete the report. Try again.',
    'dashboard.cancel_error': 'Could not cancel the report. Try again.',
    'dashboard.post_delete_confirm': 'Delete this post permanently?',
    'dashboard.post_cancel_confirm': 'Withdraw your post? It will be marked as expired.',
    'dashboard.weather_clear': 'Clear',
    'dashboard.weather_mostly_clear': 'Mostly clear',
    'dashboard.weather_partly_cloudy': 'Partly cloudy',
    'dashboard.weather_cloudy': 'Cloudy',
    'dashboard.weather_fog': 'Fog',
    'dashboard.weather_frost_fog': 'Frost fog',
    'dashboard.weather_light_drizzle': 'Light drizzle',
    'dashboard.weather_moderate_drizzle': 'Moderate drizzle',
    'dashboard.weather_dense_drizzle': 'Dense drizzle',
    'dashboard.weather_light_rain': 'Light rain',
    'dashboard.weather_moderate_rain': 'Moderate rain',
    'dashboard.weather_heavy_rain': 'Heavy rain',
    'dashboard.weather_light_snow': 'Light snow',
    'dashboard.weather_moderate_snow': 'Moderate snow',
    'dashboard.weather_heavy_snow': 'Heavy snow',
    'dashboard.weather_light_showers': 'Light showers',
    'dashboard.weather_moderate_showers': 'Moderate showers',
    'dashboard.weather_violent_showers': 'Violent showers',
    'dashboard.weather_thunderstorm': 'Thunderstorm',
    'dashboard.weather_light_hail_storm': 'Light hail storm',
    'dashboard.weather_heavy_hail_storm': 'Heavy hail storm',
    'dashboard.weather_unknown': 'Unknown',
    'crisis.default_meeting_place': 'Primary School No. 12',
    'crisis.default_contact_1_name': 'Mom',
    'crisis.default_contact_2_name': 'John (Neighbor)',
    'crisis.browser_no_gps': 'Your browser does not support geolocation.',
    'crisis.location_error_perms': 'Could not obtain location. Please grant permissions.',
    'crisis.wait_location_error': 'Please wait for your location to be detected or enter valid coordinates before continuing.',
    'crisis.manual_location_prefix': 'Manual Location',
    'crisis.gps_location_prefix': 'GPS Location',
    'crisis.default_report_title': 'Crisis Report',
    'crisis.default_report_desc': 'Incident of type {type} reported in zone {zone}.',
    'crisis.zone_not_specified': 'not specified',
    'crisis.contact_name_placeholder': 'Ex: Mom or John',
    'crisis.contact_phone_placeholder': 'Ex: 5491123456789',
    'crisis.emergency_label': 'Emergencies',
    'crisis.latitude_placeholder': 'Latitude',
    'crisis.longitude_placeholder': 'Longitude',
    'crisis.safe_place_defined': 'Defined Safe Place',
    'crisis.done': 'DONE',
    'crisis.place_name_placeholder': 'Place name',
    'crisis.change_place': 'CHANGE PLACE',
    'crisis.emergency_contacts': 'Emergency Contacts',
    'crisis.edit': 'Edit',
    'crisis.name_placeholder': 'Name',
    'crisis.phone_placeholder': 'Phone',
    'crisis.cancel': 'CANCEL',
    'crisis.update': 'UPDATE',
    'crisis.save': 'SAVE',
    'crisis.cut_guide': 'Shut-off Guide',
    'crisis.cut_guide_desc': 'Follow these instructions to minimize risks in your home.',
    'crisis.step_x_of_y': 'Step {step} of {total}',
    'crisis.previous': 'PREVIOUS',
    'crisis.next': 'NEXT',
    'crisis.system_reminders_on': 'SYSTEM: Preventive reminders scheduled every 4 hours.',
    'crisis.system_reminders_off': 'SYSTEM: Preventive reminders deactivated.',
    'crisis.calling_911': 'Calling 911...',
    'crisis.desktop_call_hint': 'Direct call function is available only on mobile devices',
    'landing.team_role_vision': 'Vision and Strategy',
    'landing.team_bio_vision': 'Drives the project vision and transforms ideas into concrete actions with real impact.',
    'landing.team_role_leadership': 'Leadership and Management',
    'landing.team_bio_leadership': 'Organizes and leads the team, ensuring everything works and moves forward with purpose.',
    'landing.team_role_community': 'Community Development',
    'landing.team_bio_community': 'Connects the community and creates spaces where people get involved and participate.',
    'landing.team_role_edu': 'Communication and Education',
    'landing.team_bio_edu': 'Communicates, educates, and turns environmental awareness into action.',
    'landing.team_role_analysis': 'Environmental Analysis',
    'landing.team_bio_analysis': 'Passionate about water care, analyzes and seeks solutions to prevent environmental issues.',
    'landing.ods_3_title': 'Health and Well-being',
    'landing.ods_3_desc': 'We prevent pollution spots and vector-borne diseases.',
    'landing.ods_6_title': 'Clean Water',
    'landing.ods_6_desc': 'We prevent waste from reaching the water and contaminating groundwater.',
    'landing.ods_11_title': 'Sustainable Cities',
    'landing.ods_11_desc': 'We improve citizen participation and urban management.',
    'landing.ods_13_title': 'Climate Action',
    'landing.ods_13_desc': 'We prepare the community to respond to extreme events.',
    'landing.years_old': 'years old',
    'landing.ods_label': 'SDG',
    'reports.timeline_title': 'Evolution History',
    'reports.add_update': 'Add update',
    'reports.mark_resolved': 'Mark as resolved',
    'reports.report_aggravation': 'Report aggravation',
    'reports.recent_update': 'Recent',
    'reports.initial_report': 'Initial Report',
    'reports.start_node': 'Start',
    'reports.update_title': 'Update',
    'reports.new_status_label': 'New Status',
    'reports.change_desc_label': 'Change Description',
    'reports.change_desc_placeholder': 'What changed? What actions were taken?',
    'reports.new_evidence_label': 'New Evidence (Optional)',
    'reports.upload_evidence_placeholder': 'Upload Evidence Photo',
    'reports.confirm_btn': 'Confirm',
    'reports.saving': 'Saving...',
    'reports.update_error': 'Error adding update. Try again.',
    'dashboard.admin': 'Administrator',
    'dashboard.guardian': 'Guardian',
    'profile.xp_points': 'XP Points',
    'profile.xp_to_next': '{xp} XP left for Level {level}',
    'profile.achievements': 'Achievements',
    'profile.no_achievements': 'No achievements yet! Keep participating.',
    'community.status_all': 'All',
    'community.status_available': 'Available',
    'community.status_reserved': 'Reserved',
    'community.status_expired': 'Expired',
    'community.status_delivered': 'Delivered/Resolved',
    'community.delete_post_admin': 'Delete post (admin)',
    'community.withdraw_post': 'Withdraw my post',
    'community.no_description': 'No additional description.',
    'dashboard.crisis_desc': 'Quick access to service cutoff guides, emergency contacts, and neighborhood meeting points. Activate it when you need to act fast.',
    'dashboard.default_alias': 'EcoWarrior',
    'dashboard.commitment_default': 'Committed to the neighborhood',
    'carousel.hero_tag': 'New',
    'carousel.hero_title': 'TODAY YOUR NEIGHBORHOOD NEEDS YOU',
    'carousel.hero_desc': 'Every report helps prevent risks and care for the community.',
    'carousel.cycle_title': 'The EcoWarriors Cycle',
    'carousel.cycle_desc': '4 stages to transform your neighborhood and care for your neighbors.',
    'carousel.resources_title': 'Resources and Presentations',
    'carousel.resources_desc': 'Learn more about the project and the technology that makes it possible.',
    'carousel.video_presentation': 'Watch presentation',
    'carousel.video_technical': 'Technical video',
    'carousel.contact_title': 'Have any questions?',
    'carousel.contact_desc': 'Write to us and we will respond shortly.',
    'auth.login_title': 'Welcome back',
    'auth.signup_title': 'Join the network',
    'auth.forgot_title': 'Recover access',
    'auth.login_subtitle': 'Your neighborhood was waiting for you.',
    'auth.signup_subtitle': 'Become an active sensor for your community.',
    'auth.forgot_subtitle': 'We will send you a link to reset your password.',
    'auth.alias_label': 'Agent Alias',
    'auth.alias_placeholder': 'e.g., GreenGuardian',
    'auth.zone_label': 'Zone / Commune',
    'auth.zone_placeholder': 'e.g., Commune 4',
    'auth.commitment_label': 'Your Commitment',
    'auth.commitment_placeholder': 'e.g., Clean my block',
    'auth.email_label': 'Email Address',
    'auth.email_placeholder': 'agent@ecowarriors.com',
    'auth.password_label': 'Password',
    'auth.confirm_password_label': 'Confirm',
    'auth.forgot_password_link': 'Forgot your password?',
    'auth.or_continue': 'Or continue with',
    'auth.google_continue': 'Continue with Google',
    'auth.google_reset_hint': 'If you signed up with Google, you don\'t need to reset your password. Just use the "Continue with Google" button.',
    'auth.google_account_detected': 'Google account detected',
    'auth.login_google': 'Log in with Google',
    'auth.reset_instructions': 'Enter your email to receive a recovery link.',
    'auth.have_account': 'Already an EcoWarrior? Log in',
    'auth.no_account': 'No account? Join the network',
    'auth.back_to_login': 'Back to login',
    'auth.create_account': 'Create Account',
    'auth.send_link': 'Send Link',
    'auth.login_button': 'Log In',
    'auth.error_email_required': 'Email is required',
    'auth.error_alias_required': 'Agent alias is required',
    'auth.error_password_min': 'Password must be at least 6 characters',
    'auth.error_password_mismatch': 'Passwords do not match',
    'auth.error_zone_required': 'Zone of responsibility is required',
    'auth.error_password_required': 'Password is required',
    'auth.error_unexpected': 'An unexpected error occurred',
    'auth.error_email_in_use': 'This email is already registered',
    'auth.error_invalid_email': 'Invalid email',
    'auth.error_invalid_credentials': 'Incorrect credentials',
    'auth.error_too_many_requests': 'Too many attempts. Try again later.',
    'auth.success_reset_sent': 'A recovery link has been sent to your email.',
    'auth.error_google_unauthorized': 'This domain is not authorized in Firebase. Contact the administrator.',
    'auth.error_google_popup_blocked': 'The browser blocked the popup. Allow popups for this site and try again.',
    'auth.error_google_popup_closed': 'You closed the Google window before completing the process.',
    'auth.error_google_cancelled': 'Operation cancelled. Try again.',
    'auth.error_user_not_found': 'We couldn\'t find an account with that email.',
    'auth.error_invalid_email_format': 'The email format is not valid.',
    'auth.error_reset_failed': 'Could not send recovery email. Please try again.',
    'auth.resend_in': 'Resend in',
    'dashboard.flood_risk': '⚠️ Flood risk',
    'reports.image_mismatch': 'Image does not match description.',
    'reports.ia_unclear': 'AI uncertain. Upload a clearer photo.',
    'reports.error_no_image': 'You must upload at least one image.',
    'reports.geo_not_supported': 'Geolocation not supported.',
    'reports.ai_key_missing': 'Configuration error: AI key is not set.',
    'reports.ai_processing_error': 'AI could not process the image. Try with another photo.',
    'reports.db_save_error': 'Error saving the report to the database.',
    'reports.analyze_error': 'Error analyzing the report. Please try again.',
    'reports.analysis_error': 'We couldn\'t analyze the report automatically. Please try describing it in more detail.',
    'reports.edit_data': 'Edit Data',
    'reports.unknown_error': 'Unknown error',
    'reports.approximate_location': 'Approximate location',
    'community.volunteer_network': 'Join the Emergency Volunteer Network',
    'validation.phone_invalid': 'Enter a valid phone number (e.g. +5491123456789)',
    'validation.name_invalid': 'Name must be between 2 and 40 characters',
    'validation.description_min': 'Description must be at least 10 characters',
    'validation.title_invalid': 'Title must be between 5 and 100 characters',
    'validation.coordinate_invalid': 'Invalid coordinate',
  }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('app_lang') as Language) || 'es');
  const [notificationsEnabled, setNotificationsEnabled] = useState<boolean>(() => localStorage.getItem('app_notifications') !== 'false');
  const [privacyMode, setPrivacyMode] = useState<PrivacyMode>(() => (localStorage.getItem('app_privacy') as PrivacyMode) || 'active');
  // Product requirement: always start in light mode on each app load.
  const [darkMode, setDarkMode] = useState<boolean>(false);

  useEffect(() => {
    localStorage.setItem('app_lang', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('app_notifications', notificationsEnabled.toString());
  }, [notificationsEnabled]);

  useEffect(() => {
    localStorage.setItem('app_privacy', privacyMode);
  }, [privacyMode]);

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const [alertConfig, setAlertConfig] = useState<{ isOpen: boolean; title: string; message: string } | null>(null);
  const [confirmConfig, setConfirmConfig] = useState<{ isOpen: boolean; title: string; message: string; onConfirm: () => void } | null>(null);

  const showAlert = (title: string, message: string) => {
    setAlertConfig({ isOpen: true, title, message });
  };

  const showConfirm = (title: string, message: string, onConfirm: () => void) => {
    setConfirmConfig({ isOpen: true, title, message, onConfirm });
  };

  return (
    <SettingsContext.Provider value={{ 
      language, 
      setLanguage, 
      notificationsEnabled, 
      setNotificationsEnabled, 
      privacyMode, 
      setPrivacyMode,
      darkMode,
      setDarkMode,
      t,
      showAlert,
      showConfirm
    }}>
      {children}
      
      {/* Global Alert Modal */}
      {alertConfig?.isOpen && (
        <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-stormy-teal/40 backdrop-blur-md">
          <div className="bg-white dark:bg-slate-900 w-full max-w-md rounded-[2rem] sm:rounded-[2.5rem] shadow-2xl flex flex-col overflow-hidden p-6 sm:p-8 space-y-6">
            <h3 className="text-lg sm:text-xl font-display font-black text-stormy-teal dark:text-maya-blue uppercase tracking-tighter text-center">
              {alertConfig.title}
            </h3>
            <p className="text-zinc-600 dark:text-slate-300 font-medium text-center">
              {alertConfig.message}
            </p>
            <button
              onClick={() => setAlertConfig(null)}
              className="w-full py-4 bg-emerald-action text-white rounded-2xl font-bold uppercase tracking-widest text-xs"
            >
              {t('common.close')}
            </button>
          </div>
        </div>
      )}

      {/* Global Confirm Modal */}
      {confirmConfig?.isOpen && (
        <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-stormy-teal/40 backdrop-blur-md">
          <div className="bg-white dark:bg-slate-900 w-full max-w-md rounded-[2rem] sm:rounded-[2.5rem] shadow-2xl flex flex-col overflow-hidden p-6 sm:p-8 space-y-6">
            <h3 className="text-lg sm:text-xl font-display font-black text-stormy-teal dark:text-maya-blue uppercase tracking-tighter text-center">
              {confirmConfig.title}
            </h3>
            <p className="text-zinc-600 dark:text-slate-300 font-medium text-center">
              {confirmConfig.message}
            </p>
            <div className="grid grid-cols-2 gap-4">
              <button
                onClick={() => setConfirmConfig(null)}
                className="py-4 bg-zinc-100 dark:bg-slate-800 text-zinc-600 dark:text-slate-300 rounded-2xl font-bold uppercase tracking-widest text-xs"
              >
                {t('common.cancel')}
              </button>
              <button
                onClick={() => {
                  confirmConfig.onConfirm();
                  setConfirmConfig(null);
                }}
                className="py-4 bg-emerald-action text-white rounded-2xl font-bold uppercase tracking-widest text-xs"
              >
                {t('common.confirm')}
              </button>
            </div>
          </div>
        </div>
      )}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) throw new Error('useSettings must be used within a SettingsProvider');
  return context;
};
